
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SUBMODULE_STRATEGY: recursive

# for older versions of Gitlab runner
#before_script:
#  - git submodule sync --recursive
#  - git submodule update --init --recursive

before_script:
  - ls -al

cache:
  paths:
    - .m2/repository/
    - "*/target"

stages:
  - build
  - test
  - package
  - verify

Build:
  image: maven:latest
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

Test:
  image: maven:latest
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - "*/target/site/jacoco"
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"

Package:
  image: maven:latest
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - "*/target/*.jar"

Verify:
  image: maven:latest
  stage: verify
  script:
    - mvn $MAVEN_CLI_OPTS verify -DskipTests
