
spring:
  web-utils:
    tasks:
      maxPoolSize: 100
      corePoolSize: 20
      queueCapacity: 100
      threadNamePrefix: Async-Exec-
      scheduledTasksPoolSize: 40
      scheduledTasksPoolNamePrefix: Scheduling-
    lang-messages:
      enabled: true
      defaultLocale: en
      supportedLocales:
        - en
        - es
      messageBasenames:
        - "classpath:strings/messages"
        - "classpath:messages/messages"
        - "classpath:messages"
        - "classpath:ValidationMessages"
        - "classpath:strings/ValidationMessages"
    data:
      enabled: true
      entities-package: com.some.package
      persistence-unit: utils
      heroku:
        jdbc-url-template: jdbc:_DB_TYPE_://_HOST_:_PORT__PATH_?currentSchema=_SCHEMA_
        url-env-name: HEROKU_DB_URL
        db-schema: public
        db-type: postgresql
      heroku-datasource:
        # Pool Properties
        maximumPoolSize: ${spring.web-utils.data.datasource.maximumPoolSize}
        minimumIdle: ${spring.web-utils.data.datasource.minimumIdle}

        #Connection test timing and intervals properties
        connectionTimeout: ${spring.web-utils.data.datasource.connectionTimeout}
        idleTimeout: ${spring.web-utils.data.datasource.idleTimeout}
        maxLifetime: ${spring.web-utils.data.datasource.maxLifetime}

      datasource:
        # Connection Properties
        #driver-class-name: org.postgresql.Driver
        #jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
        #username: dbo_admin
        #password: root

        # Pool Properties
        maximumPoolSize: 10
        minimumIdle: 1

        #Connection test timing and intervals properties
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1200000
    web:
      allow-all-cors: false
    security:
      actuator:
        enabled: false
        security-realm: Web-Utils powered Backend
        user: actuator
        password: default
      oauth2-server:
        enabled: false
        signing-key: 8B9kTV0FfUwa76R #https://www.random.org/strings/ 15 length
      oauth2-resource:
        enabled: false
        local-resource-id: server-resource-id
        secured-matchers: >
          /**/authenticated/**,
          /**/secured/**
        remote-token-services:
          enabled: false
          client-id: my_client_id
          client-secret: my_client_secret
          check-token-url: http://external.oauth2server.com/oauth/check_token

